image: $CI_REGISTRY/f329-tutoriais/docker:latest

stages:
  - images
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive


create images:
  stage: images
  script:
    - sh recursos/runpy.sh
  artifacts:
    name: images
    paths:
      - recursos/*/*.pgf


build document:
  stage: build
  script:
    - latexmk -pdf main.tex -shell-escape
    - mv main.pdf python.pdf
  artifacts:
    name: document
    paths:
      - python.pdf
