image: aergus/latex

variables:
  GIT_SUBMODULE_STRATEGY: recursive


before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update && apt-get install -y latexmk python3 python3-pygments
  - ln -s $(which python3) $(dirname $(which python3))/python

make pdf:
  script:
    - latexmk -pdf main.tex -shell-escape
    - mv main.pdf python.pdf
  artifacts:
    paths:
      - python.pdf
