image: aergus/latex

stages:
  - images
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive


before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -y
  - apt-get install -y latexmk python3
    python3-numpy python3-scipy python3-pandas
    python3-matplotlib python3-pygments
  - ln -s $(which python3) $(dirname $(which python3))/python

create images:
  stage: images
  script:
    - sh recursos/runpy.sh
  artifacts:
    name: images
    paths:
      - recursos/*/*.pgf


build document:
  stage: build
  script:
    - latexmk -pdf main.tex -shell-escape
    - mv main.pdf python.pdf
  artifacts:
    name: document
    paths:
      - python.pdf
